import React from 'react'

export default function Conclusie() {
    return (
        <div className='container'>
            <h3>Onderzoeksvraag</h3>
            <p className='text-primary'>Hoe kunnen we als school kansarme gezinnen binnen de evolutie van sociale ongelijkheid optimaal ondersteunen zodat deze kinderen de kans krijgen om zich maximaal te ontwikkelen waardoor het verschil tussen kansarme en kansrijke gezinnen kleiner wordt. </p>

            <p>Vanuit ons onderzoek zijn we de rol van het onderwijs gaan beschrijven in 3 categorieën: signaleren, ondersteunen en stimuleren. </p>
            <div className='ms-5'>
                <p>In signaleren is het belangrijk dat de school kansarmoede gaat herkennen. Dit begint al vanaf de inschrijving in de basisschool. Hierbij is het onze belangrijke taak om kansarmoede in de klas op te merken. Hierbij vinden wij het van groot belang dat een leerkracht zich gaat inlezen over wat kansarmoede inhoudt. </p>
                <p>Als leerkracht ondervinden wij dat communicatie met ouders in armoede vaak moeilijk verloopt en dat ze minder betrokken lijken. Toch dienen wij ons best te doen om met deze ouders in gesprek te gaan, zodat we de thuissituatie van de kinderen beter kunnen inschatten. </p>
                <p>Als leerkracht kunnen wij het verschil maken door een positieve houding en aanpak t.o.v. alle kinderen te hebben. We koppelen dit aan functioneel geheel 2 ‘De leerkracht als opvoeder’. We hebben als leerkracht de taak om oog te hebben voor signalen van kansarmoede zoals onverzorgde kinderen, kinderen met kapotte kledij, ongezonde en/of lege brooddozen, stille teruggetrokken kinderen. Onze taak is om kansarmoede bespreekbaar te maken met ouders, zodat ze ondersteuning kunnen krijgen en de kinderen terecht komen in een betere leef- en leersituatie. Hierdoor werkt de leerkracht ook aan een positief klasklimaat voor alle kinderen zodat de kinderen zich veilig en vertrouwd voelen in de schoolomgeving. </p>
                <p>Ook helpt de leerkracht de kinderen op weg naar de integratie binnen onze maatschappij, en tracht de vicieuze cirkel van armoede te doorbreken. De leerkracht helpt het kind om het zo ver mogelijk tot ontwikkeling te brengen, aangezien de sociale context ervoor zorgt dat de ontwikkeling van een kind stagneert of stroef loopt.</p>
                <p>Vanuit onze eigen visie vinden we het belangrijk om hoge verwachtingen te hebben naar alle kinderen in de klas. We willen hen niet onderschatten, waardoor ze ontwikkelingskansen zouden mislopen.</p>
                <p>Na het signaleren kunnen er vervolgstappen gezet worden zoals het bespreekbaar maken en het betrekken van andere organisaties. Het is essentieel om kansarmoede bespreekbaar te maken met alle betrokken partijen zoals de leerlingen, de ouders en de onderwijsinstellingen.</p>
                <p>We gaan vervolgens over naar ondersteunen. Om kansenongelijkheid tegen te gaan, dient de school alle kinderen de kans te geven om helemaal tot ontwikkeling te komen. Wij vinden het belangrijk om aan te sluiten bij de behoeften van alle kinderen. </p>
                <p>Opvoedingsondersteuning interventies helpen ouders om hun kinderen vaardigheden bij te brengen en tracht de ouders hun attitude te veranderen. Als de attitude van de ouders verandert kunnen ze de kinderen meer vaardigheden bij brengen en verandert hun gedrag t.o.v. de school, wat ook een positief effect heeft op de ontwikkeling van een kind. </p>
                <p>Nu kansarmoede bespreekbaar is gemaakt is het belangrijk dat de school passende ondersteuning geeft aan de ouders. Dit doet de school door hen door te verwijzen naar organisaties die gericht zijn op armoedebestrijding. Om als onderwijsprofessional ouders te kunnen doorverwijzen naar dergelijke instanties, vinden wij het essentieel dat wij als leerkracht voldoende op de hoogte zijn over welke organisaties er bestaan en ingeschakeld kunnen worden. Hierbij kan er ook steeds beroep gedaan op de website van ‘de Sociale Kaart’. (Sociale Kaart, z.d.)</p>
                <p>Binnen het onderwijs zijn er bepaalde factoren die ervoor zorgen dat sommige kinderen meer kansen krijgen om volop te ontwikkelen dan andere, dit is een vorm van meritocratie. Wij willen dit gegeven tegengaan als leerkracht. Ons hiervan bewust zijn is al een eerste stap in de goede richting. Verder kunnen we dit ondersteunen door kinderen als geheel te zien en ons niet enkel te baseren op prestaties, capaciteiten en talenten.</p>
                <p>In de fase van ondersteunen is het belangrijk om in gesprek te blijven gaan met de ouders. We dienen te praten over wat zij belangrijk vinden in de ondersteuning. Ook dienen we aandachtig te luisteren en dit met een oprechte houding naar de ouders toe. Wij vinden het van groot belang om hoog in te zetten op ouderbetrokkenheid, want ouders zijn de belangrijkste partners in onderwijs en blijven de eerste opvoeders. Door ouders te betrekken bij de school, krijgen ze een veilig gevoel in de schoolomgeving, wat een open communicatie met zich meebrengt. Ook trekt dit veilige gevoel zich door naar de kinderen zelf, want hoe meer welkom de ouders zich voelen in de onderwijsinstelling van hun kind, hoe beter de kinderen zich hier voelen.  </p>
                <p>De school kan de ouders ondersteunen door de schoolkosten terug te dringen om gelijkheid te verkrijgen. Dit is een vorm van proportioneel universalisme. </p>
                <p>Wij hebben opgemerkt dat partners een onmisbare schakel zijn binnen de evolutie van kansarmoede. Ze kunnen ouders en/of scholen ondersteuning bieden waar nodig. Wij vonden de volgende partners via de sociale kaart: CLB, OCMW, Rode Kruis en Welzijnszorg. Wij hebben echter opgemerkt dat er meerdere partners te vinden zijn rond kansarmoede maar dat deze niet geregistreerd staan op de Sociale Kaart. Wij denken wel dat deze partners ook nuttig kunnen zijn om armoede te bestrijden. Pelicano, Koogo, Krijt vzw, Onderwijsnetwerk Antwerpen, Kaap zijn hier voorbeelden van. </p>
                <p>Alle 4 onze partners hebben een duidelijke link met het onderwijs. Wij, als leerkracht vinden de partner Welzijnszorg het meest toegankelijk. Zij bieden educatieve materialen aan om rond kansarmoede in de klas te werken. Dit maakt het toegankelijker doordat hier minder partijen bij betrokken zijn, je raakt niet aan de persoonlijkheid van mensen. Je maakt dit bespreekbaar in de klas zonder iemand persoonlijk aan te spreken. </p>
                <p>Het CLB is al gekend bij ouders waardoor de barrière voor een eventuele samenwerking tussen school en ouders kleiner wordt. Ze worden, mits toestemming van ouders, ingezet bij overlegmomenten wanneer er zich problemen voordoen. Kansenbevordering is iets waar het CLB zich hard voor maakt. Signaleren zien zij als belangrijkste voorwaarde om tot kansenbevordering te kunnen komen.  </p>
                <p>Het Brugfiguren project kan gratis ingezet worden. Het verkleint de kloof tussen de school- en thuissituatie. Ze helpen zowel thuis als op de school met huiswerken en/of activiteiten. Wij denken dat dit voor ouders 2 kanten kan opgaan: Enerzijds kan dit als positief ervaren worden, ze kunnen op een laagdrempelige manier een gesprek aangaan met ouders doordat dit plaatsvindt in hun eigen omgeving. Anderzijds kan dit als negatief ervaren worden omdat ze zich schamen voor hun thuissituatie. Een bedreiging aan dit project is dat er een lerarentekort is, waardoor er meer vraag is naar hulp, ze kunnen niet voldoen aan vraag en aanbod. Door lerarentekort loopt het signaleren van kansarmoede gevaar. Wij concluderen hieruit dat dit een heel sterk project is in het onderwijs, maar dat het nog niet helemaal naar wensen kan uitgevoerd worden.</p>
                <p>Het OCMW richt zich onder andere op een stuk financiële ondersteuning om iedereen de mogelijkheid te geven om te participeren in de schoolomgeving. Ze zetten zich in om een breed draagvlak te creëren met andere partners. Dit doen ze door elkaar te versterken en van elkaar te leren. Samen bereik je meer, ze streven dus naar veel samenwerking met een diversiteit aan partners. De school heeft een belangrijke rol in het kenbaar maken van het bestaan van het OCMW naar ouders. Het OCMW ziet helaas wel bedreigingen in het tekort aan onderwijzend personeel. </p>
                <p>We vinden het OCMW een zeer belangrijke partner aangezien zij ervoor kunnen zorgen dat een kansarm gezin uit de financiële vicieuze cirkel geraakt. Wel willen we vermelden dat het enorm moeilijk kan zijn om als onderwijsprofessional het gesprek met een gezin aan te gaan, over het feit dat ze in kansarmoede leven en misschien wel hulp kunnen gebruiken. Verder dienen ouders ermee akkoord te gaan dat een partner zoals het OCMW wordt ingeschakeld. </p>
                <p>Na de besproken bovenstaande partners, willen we zeker benadrukken dat na ons onderzoek, er sterk is uitgekomen dat ouders de belangrijkste partners zijn. Zij blijven de eerste opvoeders en vormen de brug tussen de thuissituatie en de school. Zonder toestemming van de ouders, kunnen wij, als onderwijsprofessionals niet samenwerken met het CLB, OCMW en het Rode kruis. Hierbij willen we het belang van ouders nog eens extra benadrukken. </p>
                <p>Na het ondersteunen gaan we over naar stimuleren. Het blijft moeilijk om de ongelijke startpositie op te vangen in het onderwijssysteem waardoor we niet kunnen werken aan gelijke kansen om de eindstreep te behalen. Doordat dit de sociale ongelijkheden versterkt, zorgt dit voor een maatschappelijke kwetsbaarheid bij kinderen en jongeren. Het schoolparcours is voor vele kinderen en jongeren een moeilijk parcours dat uitsluit en kwetst. Wij vinden het belangrijk om ouders te stimuleren om thuis zo veel mogelijk taal aan te bieden, we denken daarbij aan voorlezen of bijvoorbeeld het aanbieden van gratis educatieve uitstappen. De ouders moeten zich betrokken voelen bij de school zodat de leerkrachten een goede invloed hebben op de ouders waardoor ze meewerken aan een educatief aanbod. Zo hopen we om deze sociale ongelijkheid te kunnen terugdringen. </p>
                <p>We vinden dat leerkrachten moeten inzetten op ouderbetrokkenheid. Ouderbetrokkenheid heeft een positief effect op de schoolprestaties. We moeten ouders stimuleren om interesse te tonen in het schoolwerk van hun kind en waar nodig samen met hun kind voor school te werken. Ze kunnen zelf ook nog leren uit de leerstof van hun kind. De sociaaleconomische status geeft aan dat het bevorderen van ouderbetrokkenheid voor kansarme gezinnen grotere voordelen kan opbrengen dan voor kansrijke gezinnen. Ze vertrekken van een lager basisniveau. Het nadeel van ouderbetrokkenheid is de hoge opportuniteitskosten, in de vorm van tijdsinvestering. De tijd gebruiken ze vaak voor andere doeleinde zoals overleven.</p>
                <p>Het stimuleren van de positieve ontwikkeling is van groot belang in het onderwijs. De cognitieve vaardigheden en levensvaardigheden of ‘doe-vaardigheden’ zijn van groot belang. Hierdoor leren kinderen beter met moeilijke situaties omgaan zoals armoede en worden de sociale kansen vergroot. </p>
                <p>Wij vinden dat er aandacht moet worden besteed aan financiële voorlichting op school. Hierin hebben wij als leerkracht een belangrijke taak. Zo kunnen we kinderen de waarde van geld leren kennen en hen leren dat inkomsten en uitgaven in balans moet zijn. Het is de taak van ons als leerkracht om over financiën te praten. Dit niet enkel om te achterhalen wie er in armoede leeft maar ook om kinderen te laten voelen dat ze niet alleen zijn. Er zijn steeds meer projecten die gebaseerd zijn op armoede en financiële educatie. Het is voor alle kinderen interessant om te weten wat armoede is en om te leren hoe ze moeten sparen en hoe ze hun budget kunnen beheren. Een goed project om dit in een kleuterklas bespreekbaar te maken is het project van één van onze onderzochte partners Welzijnszorg genaamd ‘Jordy’. </p>

                <a href='https://welzijnszorg.be/jordy' target='_blank'> <button className='btn btn-primary mb-3'>Naar Jordy</button> </a>
             

                <p>We zijn hier zelf erg enthousiast over dat twee van ons dit gaan voorstellen aan de school waar zij werken. In deze school zijn veel kinderen die in (kans)armoede leven. We vonden helaas wel dat dit project moeilijk te vinden was. Een tip voor deze organisatie om het meer bekendheid te geven.</p>
                <p>Ouders kunnen we doorverwijzen naar de juiste instanties die gericht zijn om hen te helpen bij financiën. Via de website van armoedebestrijding kunnen ouders terecht met hulpvragen. Hier staan ook partners en helpende handen omschreven.</p>
                <p>Vanuit een sterke wil naar een democratische maatschappij, waarin iedereen, ongeacht de status van een gezin, een gelijke positie heeft binnen de samenleving, vinden we het een voorwaarde dat de leerkracht inzet op participatie van zowel kinderen als ouders zodat zij ook hun steentje kunnen bijdragen tot het vormen van de school. </p>
                <p>Wij vinden het heel belangrijk om ouders te stimuleren om met hun kinderen in het park te gaan wandelen om tot rust te komen, aangezien dit het stressniveau verlaagt en het gratis is.</p>
                <p>In sommige gemeenten wordt er gewerkt met een vrijetijdspas. Wij vinden het belangrijk om als leerkracht ouders te stimuleren om een vrijetijdspas aan te schaffen zodat kinderen goedkoper of gratis kunnen deelnemen aan activiteiten in de buurt. Zo worden kinderen minder uitgesloten en kunnen ze hun sociale contacten onderhouden. Ook vergroot het kansen op werk en zorgt het voor een betere thuissfeer. Door stress te verminderen kunnen mensen beter vooruitkijken en kunnen ze betere beslissingen nemen. </p>
                <p>Als we onze conclusie nu koppelen aan het boek van Biesta, ‘Goed onderwijs en de cultuur van het meten’, dan zie we in het hoofdstuk: ‘Waar is het onderwijs voor?’ (Biesta, 2012) drie verschillende functies voor wat goed onderwijs is. Deze kunnen we linken aan onze maatschappelijke evolutie, namelijk kansarmoede binnen de sociale ongelijkheid. Kwalificatie heeft bij onze conclusie bijvoorbeeld betrekking tot de (financiële) educatie. Door kinderen op jonge leeftijd bewust te maken van wat kansarmoede is, gaan ze op latere leeftijd weten dat er ondersteuning bestaat en waar ze deze kunnen terugvinden. Het is de taak van ons als leerkracht om kinderen bewust te maken van deze kennis en begrippen omtrent kansarmoede. Wanneer de leerkracht alle kinderen hoogwaardig inschat en alle kinderen gelijke kansen biedt, vormt zich subjectwording. Leerlingen moeten zichzelf kunnen en durven worden. Ze moeten kunnen ontdekken wie ze zijn en moeten zichzelf durven zijn, ongeacht uit welk gezin ze komen. Als leerkracht speel je hierbij een grote rol. Socialisatie zien we terug in de verschillende partners, hierbij denken wij bijvoorbeeld aan het aanbieden van vrijetijdspassen waardoor kinderen de kans krijgen om sociale contacten te maken in de buurt. De ouders kunnen (eventueel via de scholen) ondersteuning aanvragen bij het OCMW, Welzijnszorg, CLB en het Rode kruis met bijvoorbeeld het brugfigurenproject. </p>
            </div>


            <p></p>
        </div>
    )
}
