import React from 'react'

export default function Conclusie() {
    return (
        <div className='container'>
            <h1>Onderzoeksvraag</h1>
            <p className='text-primary'>Hoe kunnen we als school kansarme gezinnen binnen de evolutie van sociale ongelijkheid optimaal ondersteunen zodat deze kinderen de kans krijgen om zich maximaal te ontwikkelen waardoor het verschil tussen kansarme gezinnen en kansrijke gezinnen kleiner wordt. </p>
            <p>Vanuit ons onderzoek zijn we de rol van het onderwijs gaan beschrijven in 3 categorieën: signaleren, ondersteunen en stimuleren. </p>
            <p>In signaleren is het belangrijk dat de school kansarmoede gaat herkennen. Dit begint al vanaf de inschrijving in de basisschool. De rol van de leerkracht is het opmerken van kansarmoede in de klas. De leerkracht gaat zich inlezen wat kansarmoede inhoudt. </p>
            <p>Communicatie met ouders in armoede is moeilijk, ze lijken vaak minder betrokken. Wij vinden het cruciaal om met de ouders in gesprek te gaan zodat we de thuissituatie van de kinderen te kunnen inschatten. </p>
            <p>Als leerkracht kunnen wij het verschil maken door een positieve houding t.o.v. de kinderen te hebben en ze positief aan te pakken. We koppelen dit aan functioneel geheel ‘De leerkracht als opvoeder’. We hebben als leerkracht de taak om oog te hebben voor signalen van kansarmoede, bijvoorbeeld onverzorgde kinderen, kinderen met kapotte kledij, ongezonde brooddozen… Onze taak is om kansarmoede bespreekbaar te maken met ouders zodat ze ondersteuning kunnen krijgen en de kinderen terecht komen in een betere leefsituatie. </p>
            <p>Vanuit onze eigen visie vinden we het belangrijk om hoge verwachtingen te hebben naar alle kinderen in de klas. We willen het niet onderschatten, waardoor ze ontwikkelingskansen zouden mislopen.</p>
            <p>Na het signaleren kunnen er vervolgstappen gezet worden zoals het bespreekbaar maken en het betrekken van andere organisaties. Het is essentieel om kansarmoede bespreekbaar te maken met alle betrokken partijen.</p>
            <p>We gaan vervolgens over naar ondersteunen. Vanuit kansenongelijkheid dient de school alle kinderen de kans te geven om helemaal tot ontwikkeling te komen. Wij vinden het belangrijk om aan te sluiten bij de behoefte van alle kinderen. </p>
            <p>Opvoedingsondersteuningsinterventies helpen ouders om hun kinderen vaardigheden bij te brengen en tracht de ouders hun attitude te veranderen. Als de attitude van de ouders verandert kunnen ze de kinderen meer vaardigheden bij brengen en verandert hun gedrag t.o.v. de school, wat ook een positief effect heeft op de ontwikkeling van een kind. </p>
            <p>Nu kansarmoede bespreekbaar is gemaakt is het belangrijk dat de school passende ondersteuning geeft aan de ouders. Dit doet de school door hen door te verwijzen naar organisaties die gericht zijn op armoedebestrijding. </p>
            <p>Binnen het onderwijs zijn er bepaalde factoren die ervoor zorgen dat sommige kinderen meer kansen krijgen om volop te ontwikkelen dan andere, dit is een vorm van meritocratie. Wij willen dit gegeven tegengaan als leerkracht. Ons hiervan bewust zijn is al een eerste stap in de goede richting. Verder kunnen we dit ondersteunen door kinderen als geheel te zien en ons niet enkel te baseren op prestaties, capaciteiten en talenten.</p>
            <p>In de fase van ondersteunen is het belangrijk om in gesprek te blijven gaan met de ouders. Praat over wat zij belangrijk vinden in de ondersteuning en luister aandachtig en oprecht naar de ouders.  Zet zeker hoog in op ouderbetrokkenheid want ouders zijn de belangrijkste partners in onderwijs. Door ouders te betrekken bij de school, krijgen ze een veilig gevoel in de schoolomgeving, wat een open communicatie met zich meebrengt. </p>
            <p>De school kan de ouders ondersteunen door de schoolkosten terug te dringen om gelijkheid te verkrijgen. Dit is een vorm van proportioneel universalisme. </p>
            <p>Wij hebben opgemerkt dat partners een onmisbare schakel zijn binnen de evolutie van Kansarmoede. Ze kunnen ouders ondersteuning bieden waar nodig. Wij vonden de volgende partners: CLB, OCMW, Rode Kruis en Het huis van het kind.</p>
            
            
            <p className='text-danger'>STERKE CONCLUSIE VORMEN VAN DE PARTNERS</p>
            
            
            <p>Hierna gaan we over naar stimuleren. Het blijft moeilijk om de ongelijke startpositie op te vangen in het onderwijssysteem waardoor we niet kunnen werken aan gelijke kansen om de eindstreep te behalen. Doordat dit de sociale ongelijkheden versterkt, is dit een maatschappelijke kwetsbaarheid bij kinderen en jongeren. Het schoolparcours is voor vele kinderen en jongeren een moeilijk parcours dat uitsluit en kwetst. We kunnen ouders hierbij stimuleren om thuis zo veel mogelijk taal aan te bieden, we denken daarbij aan voorlezen of bijvoorbeeld het aanbieden van gratis educatieve uitstappen. De ouders moeten zich betrokken voelen bij de school zodat de leerkrachten een goede invloed hebben op de ouders waardoor ze meewerken aan een educatief aanbod. </p>

            <p>We vinden dat leerkrachten moeten inzetten op ouderbetrokkenheid. Ouderbetrokkenheid heeft een positief effect op de schoolprestaties. We moeten ouders stimuleren om interesse te tonen in het schoolwerk van hun kind en waar nodig samen met hun kind voor school te werken. Ze kunnen zelf ook nog leren uit de leerstof van hun kind. De sociaaleconomische status geeft aan dat het bevorderen van ouderbetrokkenheid voor kansarme gezinnen grotere voordelen kan opbrengen dan voor kansrijke gezinnen. Ze vertrekken van een lager basisniveau. Het nadeel van ouderbetrokkenheid is de hoge opportuniteitskosten, in de vorm van tijdsinvestering. De tijd gebruiken ze vaak voor andere doeleinde. </p>
            
            <p>Het stimuleren van de positieve ontwikkeling is van groot belang in het onderwijs. De cognitieve vaardigheden en levensvaardigheden of ‘doe-vaardigheden’ is belangrijk waardoor kinderen beter met moeilijke situaties kunnen omgaan zoals armoede en worden de sociale kansen vergroot. </p>

            <p>Er moet aandacht worden besteed aan financiële voorlichting op school. Hierin hebben wij als leerkracht een belangrijke taak. Zo kunnen we kinderen de waarde van geld leren kennen en dat inkomsten en uitgaven in balans moet zijn. Het is de taak van ons als leerkracht om erover te praten. Dit niet enkel om te achterhalen wie er in armoede leeft maar ook om kinderen te laten voelen dat ze niet alleen zijn. Er zijn steeds meer projecten die gebaseerd zijn op armoede en financiële educatie. Het is voor alle kinderen interessant om te weten wat armoede is en om te leren hoe ze moeten sparen en hun budget moeten beheren. Ouders kunnen we doorverwijzen naar de juiste instanties die gericht zijn om hen te helpen bij financiën. Via de website van armoedebestrijding kunnen ouders terecht met hulpvragen. Hier staan ook partners en helpende handen omschreven.</p>
            
            <p>Wij vinden het heel belangrijk om ouders te stimuleren om met hun kinderen in het park te gaan wandelen om tot rust te komen, aangezien dit het stressniveau verlaagt en het is gratis. </p>
            
            <p>In sommige gemeentes werken ze met een vrijetijdspas. Wij kunnen als leerkracht ouders stimuleren om een vrijetijdspas aan te schaffen zodat kinderen goedkoper of gratis kunnen deelnemen aan activiteiten in de buurt. Zo worden kinderen minder uitgesloten en kunnen ze sociaal contact onderhouden. Ook vergroot het kansen op werk en zorgt het voor een positieve thuissfeer. Door stress te verminderen helpt het mensen vooruit te kijken en betere beslissingen te nemen. </p>
            
            <p>Als we onze conclusie nu koppelen aan het boek van Biesta, ‘Goed onderwijs en de cultuur van het meten’, dan zie we in het hoofdstuk: ‘Waar is het onderwijs voor?’ (Biesta, 2012) drie verschillende functies voor wat goed onderwijs is. Deze kunnen we linken aan onze maatschappelijke evolutie kansarmoede binnen de sociale ongelijkheid. Kwalificatie heeft bij onze conclusie bijvoorbeeld betrekking tot de (financiële) educatie. Door kinderen op jonge leeftijd bewust te maken wat kansarmoede is, gaan ze op latere leeftijd weten dat er ondersteuning bestaat en waar ze het kunnen vinden. Het is de taak van de leerkracht om de kinderen bewust te maken van deze kennis en begrippen omtrent kansarmoede. Wanneer de leerkracht alle kinderen hoogwaardig inschat en alle kinderen gelijke kansen biedt, vormt zich subjectwording. Leerlingen moeten zichzelf kunnen worden. Socialisatie zien we terug in de verschillende partners, hierbij denken wij bijvoorbeeld aan het aanbieden van vrijetijdspassen waardoor ze de kans krijgen om sociale contacten te maken in de buurt. De ouders kunnen (eventueel via de scholen) ondersteuning vragen bij het OCMW, Het huis van het kind, CLB en het Rode kruis met bijvoorbeeld het brugfigurenproject. </p>
            
            <p></p>
        </div>
    )
}
